const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),ts=require('typescript');
const {PGlite}=require('@electric-sql/pglite');const {randomUUID,createHash}=require('node:crypto');
const pg=new PGlite();let who=null;const cache={},calls=[];const identities=new Map();const objects=new Map();const setupCode='test-only-private-code';
process.env.ADMIN_SETUP_HASH=createHash('sha256').update(setupCode).digest('hex');
function prepare(sql){let args=[];const statement={bind(...values){args=values;return this},async execute(client=pg){const r=await client.query(sql,args);return {results:r.rows,meta:{changes:r.affectedRows||r.rows.length}}},async first(){return (await this.execute()).results[0]||null},async all(){return this.execute()},async run(){return this.execute()}};return statement;}
const database={prepare,batch:statements=>pg.transaction(async tx=>{const results=[];for(const s of statements)results.push(await s.execute(tx));return results;})};
const provider={auth:{async getUser(){return {data:{user:who},error:null}},async signInWithPassword({email,password}){const u=identities.get(email);if(!u||u.password!==password)return {data:{user:null},error:{message:'Invalid'}};who=u;return {data:{user:u},error:null}},async signOut({scope}={}){if(scope!=='others')who=null;return {error:null}},async updateUser({password}){who.password=password;return {error:null}},admin:{async createUser({email,password,user_metadata}){if(identities.has(email))return {data:{user:null},error:{message:'Duplicate'}};const u={id:randomUUID(),email,password,user_metadata};identities.set(email,u);await pg.query('INSERT INTO auth.users(id) VALUES($1)',[u.id]);return {data:{user:u},error:null}},async deleteUser(id){for(const [email,u] of identities)if(u.id===id)identities.delete(email);await pg.query('DELETE FROM auth.users WHERE id=$1',[id]);return {error:null}}}}};
function load(file){if(cache[file])return cache[file].exports;const m={exports:{}};cache[file]=m;const source=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const localRequire=name=>{if(name==='server-only')return {};if(name==='@/lib/database'||name==='./database')return {database};if(name==='@/lib/supabase/server'||name==='./supabase/server')return {supabase:async()=>provider,supabaseAdmin:()=>provider,configured:()=>true};if(name.startsWith('@/'))return load(name.slice(2)+'.ts');if(name.startsWith('.'))return load(path.join(path.dirname(file),name)+'.ts');return require(name);};new Function('require','exports','module',source)(localRequire,m.exports,m);return m.exports;}
provider.storage={from:()=>({async createSignedUploadUrl(path){return {data:{token:'test-upload-token',path},error:null}},async info(path){return objects.has(path)?{data:objects.get(path),error:null}:{data:null,error:{message:'Missing'}}},async remove(paths){paths.forEach(p=>objects.delete(p));return {error:null}},async createSignedUrl(path){return {data:{signedUrl:'https://storage.example.test/'+path+'?token=test'},error:null}}})};
const hub=load('app/api/hub/route.ts'),auth=load('app/api/auth/route.ts'),documents=load('app/api/documents/route.ts'),{Balance}=load('lib/finance.ts');
async function get(campus='dirty-south'){const r=await hub.GET(new Request('https://test.local/api/hub?campus='+campus));return {status:r.status,...await r.json()};}
async function post(action,data={},campus='dirty-south',self=false){const r=await hub.POST(new Request('https://test.local/api/hub',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://test.local'},body:JSON.stringify({action,campus,data,self})}));return {status:r.status,...await r.json()};}
async function account(action,data={},origin='https://test.local'){const r=await auth.POST(new Request('https://test.local/api/auth',{method:'POST',headers:{Origin:origin},body:JSON.stringify({action,...data})}));return {status:r.status,...await r.json()};}
(async()=>{
 await pg.exec('CREATE ROLE anon; CREATE ROLE authenticated; CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY); CREATE SCHEMA storage; CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);');
 await pg.exec(fs.readFileSync('supabase/migrations/202609270001_fellowship.sql','utf8'));calls.push('PostgreSQL migration applies successfully');
 assert.equal((await get()).status,401);assert.equal((await account('setup',{email:'owner@example.test',name:'Owner',password:'private-password-2026',code:'wrong'})).status,400);
 assert.equal((await account('setup',{email:'owner@example.test',name:'Owner',password:'private-password-2026',code:setupCode},'https://attacker.test')).status,403);
 assert.equal((await account('setup',{email:'owner@example.test',name:'Owner',password:'private-password-2026',code:setupCode})).status,200);const owner=who;
 assert.equal((await account('setup',{email:'other@example.test',name:'Other',password:'private-password-2026',code:setupCode})).status,400);calls.push('private one-time setup and CSRF protection');
 const invitation=await account('invite',{email:'member@example.test',campus:'dirty-south'});assert.equal(invitation.status,200);who=null;
 assert.equal((await account('activate',{email:'imposter@example.test',name:'Imposter',password:'private-password-2026',code:invitation.code})).status,400);
 assert.equal((await account('activate',{email:'member@example.test',name:'Member',password:'private-password-2026',code:invitation.code})).status,200);const member=who;
 assert.equal((await account('activate',{email:'member@example.test',name:'Member',password:'private-password-2026',code:invitation.code})).status,400);calls.push('Supabase provider delegation and email-bound invitations');
 assert.equal((await post('member',{name:'Member',email:member.email},'dirty-south',true)).status,200);
 assert.equal((await post('transaction',{amount:1})).status,403);assert.equal((await get('bonduma')).members.length,0);assert.equal((await post('member',{name:'Member'},'bonduma',true)).status,400);calls.push('member authorization and campus isolation');
 who=owner;const m=await post('member',{name:'Private Person',email:'private@example.test',phone:'private',father:'private'});assert.equal(m.status,200);
 who=member;const privateRow=(await get()).members.find(x=>x.id===m.id);assert.equal(privateRow.phone,undefined);assert.equal(privateRow.details,undefined);calls.push('private fields hidden from other members');
 who=owner;const service=await post('service',{type:'Sunday Worship Service',date:'2026-09-01',time:'09:00',venue:'Hall',usher:member.email});assert.equal(service.status,200);
 who=member;const attendance={serviceId:service.id,men:10,women:12,visitors:3,converts:1,language:'English'};assert.equal((await post('attendance',attendance)).status,200);assert.equal((await post('attendance',attendance)).status,400);calls.push('assigned usher and duplicate attendance');
 who=owner;const group=await post('group',{name:'Group',area:'Area',leader:'Leader'});assert.equal(group.status,200);
 let extra;
 for(let i=0;i<11;i++){const memberRow=await post('member',{name:'Group '+i,email:`g${i}@example.test`});assert.equal(memberRow.status,200);assert.equal((await post('assign-group',{groupId:group.id,memberId:memberRow.id})).status,i<10?200:400);extra=memberRow;}
 await assert.rejects(()=>pg.query('INSERT INTO group_members(id,campus,group_id,member_id) VALUES($1,$2,$3,$4)',[randomUUID(),'dirty-south',group.id,extra.id]),/limit of 10/);calls.push('group capacity enforced in routes and database');
 const vow=await post('vow',{memberId:m.id,purpose:'Project',amount:1000,date:'2026-09-01'});assert.equal(vow.status,200);
 const tx={amount:600,type:'Income',account:'Cash',category:'Vow',description:'Payment',date:'2026-09-01',vowId:vow.id};assert.equal((await post('transaction',tx)).status,200);assert.equal((await post('transaction',tx)).status,400);
 await assert.rejects(()=>pg.query("INSERT INTO transactions(id,campus,type,account,amount,category,description,date,vow_id,author,created_at) VALUES($1,'dirty-south','Income','Cash',600,'Vow','Payment','2026-09-01',$2,'test','now')",[randomUUID(),vow.id]),/outstanding vow/);calls.push('vow balance enforced in routes and database');
 assert.equal((await post('transaction',{amount:200,type:'Cash to bank',account:'Cash',category:'Transfer',description:'Deposit',date:'2026-09-02'})).status,200);
 assert.deepEqual(Balance((await get()).transactions),{cash:400,bank:200,income:600,expense:0});calls.push('cash transfers preserve income and combined balance');
 await pg.exec('SET ROLE anon');await assert.rejects(()=>pg.query('SELECT * FROM members'),/permission denied/);await pg.exec('RESET ROLE');await pg.exec('SET ROLE authenticated');await assert.rejects(()=>pg.query('SELECT * FROM transactions'),/permission denied/);await pg.exec('RESET ROLE');calls.push('Supabase browser roles cannot read private tables');
 const tables=(await pg.query("SELECT relname FROM pg_class WHERE relnamespace='public'::regnamespace AND relkind='r' AND NOT relrowsecurity")).rows;assert.equal(tables.length,0);calls.push('row level security enabled for every application table');
 who=member;assert.equal((await account('invite',{email:'other@example.test',campus:'dirty-south'})).status,403);assert.equal((await account('logout')).status,200);assert.equal((await get()).status,401);calls.push('invitation permissions and sign-out');

 async function docPost(data){const r=await documents.POST(new Request('https://test.local/api/documents',{method:'POST',headers:{Origin:'https://test.local'},body:JSON.stringify({campus:'dirty-south',...data})}));return {status:r.status,...await r.json()};}
 who=member;assert.equal((await docPost({action:'prepare'})).status,403);
 who=owner;const upload=await docPost({action:'prepare',title:'Test PDF',filename:'test.pdf',mime:'application/pdf',size:5000000});assert.equal(upload.status,200);
 objects.set(upload.path,{size:5000000,contentType:'application/pdf'});assert.equal((await docPost({action:'finish',id:upload.id})).status,200);
 const download=await documents.GET(new Request('https://test.local/api/documents?campus=dirty-south&id='+upload.id));assert.equal(download.status,302);assert.match(download.headers.get('location'),/^https:\/\/storage.example.test\//);
 who=member;assert.equal((await documents.GET(new Request('https://test.local/api/documents?campus=dirty-south&id='+upload.id))).status,403);calls.push('authorized direct uploads and private signed downloads');
 console.log(JSON.stringify({passed:calls.length,checks:calls},null,2));
 await pg.close();
})().catch(async e=>{console.error(e);await pg.close();process.exitCode=1;});
