import {checkOrigin} from '@/lib/auth';
import type {Statement} from '@/lib/database';
import {db,all,identity,auditStatement,textValue as str,numberValue as num,fail} from '@/lib/server';
import {roles} from '@/lib/access';
export const dynamic='force-dynamic';
const departments=['Choir','Ushering','Prayer','SMAT','Electronics','Evangelism','Follow-up','Maintenance','Secretariat','DAS','Sisters’ Welfare'];
export async function GET(request:Request){try{const campus=new URL(request.url).searchParams.get('campus')||'dirty-south';const ctx=await identity(campus);const p=ctx.permissions;const campusList=await all('SELECT * FROM campuses ORDER BY name');if(!campusList.some(c=>c.id===campus))throw new Error('Campus not found.');let members:any[]=[];if(p.members||p.academics||p.followup||p.finance||p.services||p.groups)members=await all('SELECT * FROM members WHERE campus=$1 ORDER BY name',campus);else if(ctx.member)members=await all('SELECT id,name,department,status FROM members WHERE campus=$1 ORDER BY name',campus);
if(!p.members)members=members.map(m=>({id:m.id,name:m.name,department:m.department,status:m.status,...(p.academics?{institution:m.institution,programme:m.programme,level:m.level}:{}),...(p.followup?{phone:m.phone}:{}),...(m.id===ctx.member?.id?m:{})}));
const hasMembership=!!ctx.member||Object.values(p).some(Boolean);const scope=hasMembership?campus:'__none';
const serviceList=await all('SELECT * FROM services WHERE campus=$1 ORDER BY date DESC,time',scope);
const attendanceList=(p.reports||p.services)?await all('SELECT a.*,s.type,s.date,s.time FROM attendance a JOIN services s ON s.id=a.service_id AND s.campus=a.campus WHERE a.campus=$1 ORDER BY s.date DESC',campus):[];
const tx=p.finance?await all('SELECT * FROM transactions WHERE campus=$1 ORDER BY date DESC,created_at DESC',campus):[];
const vowList=p.finance?await all('SELECT v.*,m.name,COALESCE((SELECT SUM(amount) FROM transactions t WHERE t.vow_id=v.id AND t.campus=v.campus AND t.type=\'Income\'),0) paid FROM vows v JOIN members m ON m.id=v.member_id WHERE v.campus=$1',campus):ctx.member?await all('SELECT v.*,COALESCE((SELECT SUM(amount) FROM transactions t WHERE t.vow_id=v.id AND t.campus=v.campus AND t.type=\'Income\'),0) paid FROM vows v WHERE v.campus=$1 AND v.member_id=$2',campus,ctx.member.id):[];
const groups=(p.groups||p.followup)?await all('SELECT g.*,(SELECT COUNT(*) FROM group_members gm WHERE gm.group_id=g.id) "memberCount" FROM groups g WHERE campus=$1',campus):ctx.member?await all('SELECT g.* FROM groups g JOIN group_members gm ON gm.group_id=g.id WHERE gm.member_id=$1 AND g.campus=$2',ctx.member.id,campus):[];
const groupMembers=(p.groups||p.followup)?await all('SELECT * FROM group_members WHERE campus=$1',campus):[];
const announcements=p.announcements?await all("SELECT * FROM announcements WHERE campus=$1 ORDER BY date DESC",campus):await all("SELECT * FROM announcements WHERE campus=$1 AND (audience='All members' OR audience=$2) AND date<=$3 ORDER BY date DESC",scope,ctx.member?.department||'',new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Douala'}));
const docs=p.documents?await all('SELECT * FROM documents WHERE campus=$1 ORDER BY date DESC',campus):[];
const audit=p.admin||p.members?await all('SELECT * FROM audit WHERE campus=$1 ORDER BY created_at DESC LIMIT 15',campus):[];
const grants=p.admin?await all('SELECT * FROM grants WHERE campus=$1',campus):[];
return Response.json({campuses:campusList,campus,user:{name:ctx.user.displayName,email:ctx.user.email},role:ctx.role,permissions:p,profile:ctx.member,members,services:serviceList,attendance:attendanceList,transactions:tx,vows:vowList,groups,groupMembers,announcements,documents:docs,audit,grants,departments},{headers:{'Cache-Control':'no-store'}});
}catch(e){return fail(e);}}
export async function POST(request:Request){try{checkOrigin(request);const b=await request.json() as any;const campus=str(b.campus);const exists=await db().prepare('SELECT id FROM campuses WHERE id=$1').bind(campus).first();if(!exists)throw new Error('Campus not found.');const ctx=await identity(campus);const p=ctx.permissions;const q=db();const d=b.data||{};const id=crypto.randomUUID();const now=new Date().toISOString();const author=ctx.user.email;let statement:Statement;let resultId=id;const need=(allowed:boolean)=>{if(!allowed)throw new Error('You do not have permission for this action.');};const required=(v:unknown,label:string)=>{const s=str(v);if(!s)throw new Error(label+' is required.');return s;};const date=(v:unknown)=>{const s=str(v);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(Date.parse(s)))throw new Error('Enter a valid date.');return s;};
switch(b.action){
case 'member':{const self=b.self===true;need(p.members||self);if(self){const other=await q.prepare('SELECT id FROM members WHERE campus<>$1 AND (user_id=$2 OR email=$3)').bind(campus,ctx.user.userId,ctx.user.email.toLowerCase()).first();if(other)throw new Error('A profile already exists in another campus. Ask your coordinator to arrange a transfer.');}const existing=self?ctx.member: d.id?await q.prepare('SELECT * FROM members WHERE id=$1 AND campus=$2').bind(d.id,campus).first<any>():null;const email=self?ctx.user.email.toLowerCase():required(d.email,'Email').toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('Enter a valid email address.');const detailKeys=['dob','birthplace','secondaryPhone','father','fatherPhone','fatherChurch','mother','motherPhone','motherChurch','parentsRegion','salvationDate','baptismDate','faculty','duration','academicYear','address','compound','room','occupants','accommodation','roommateNames'];const details=Object.fromEntries(detailKeys.map(k=>[k,str(d[k],1000)]));if(details.occupants&&num(details.occupants,4)<1)throw new Error('Room occupancy must be between 1 and 4.');const values=[required(d.name,'Full name'),email,str(d.phone),str(d.sex),p.members?str(d.status)||'Active':'Active',str(d.department),str(d.institution),str(d.programme),str(d.level),JSON.stringify(details)];if(existing){resultId=existing.id;statement=q.prepare('UPDATE members SET name=$1,email=$2,phone=$3,sex=$4,status=$5,department=$6,institution=$7,programme=$8,level=$9,details=$10 WHERE id=$11 AND campus=$12').bind(...values,existing.id,campus);}else{statement=q.prepare('INSERT INTO members(id,campus,user_id,name,email,phone,sex,status,department,institution,programme,level,details,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)').bind(id,campus,self?ctx.user.userId:null,...values,now);}break;}
case 'service':need(p.services);if(!/^\d{2}:\d{2}$/.test(str(d.time)))throw new Error('Select a service time.');statement=q.prepare('INSERT INTO services(id,campus,type,date,time,venue,usher) VALUES($1,$2,$3,$4,$5,$6,$7)').bind(id,campus,required(d.type,'Service'),date(d.date),d.time,required(d.venue,'Venue'),str(d.usher).toLowerCase());break;
case 'attendance':{const service=await q.prepare('SELECT * FROM services WHERE id=$1 AND campus=$2').bind(str(d.serviceId),campus).first<any>();if(!service)throw new Error('Select a scheduled service.');need(p.services||service.usher===author.toLowerCase());if(service.date>new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Douala'}))throw new Error('Record attendance after the service date.');if(!['English','French'].includes(d.language))throw new Error('Select a language.');if(num(d.visitors,100000)>num(d.men,100000)+num(d.women,100000))throw new Error('Visitors must not exceed total attendance.');statement=q.prepare('INSERT INTO attendance(id,campus,service_id,men,women,visitors,converts,language,notes,author,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)').bind(id,campus,service.id,num(d.men,100000),num(d.women,100000),num(d.visitors,100000),num(d.converts,100000),d.language,str(d.notes,2000),author,now);break;}
case 'group':need(p.groups);statement=q.prepare('INSERT INTO groups(id,campus,name,area,leader,assistant,meeting) VALUES($1,$2,$3,$4,$5,$6,$7)').bind(id,campus,required(d.name,'Group name'),required(d.area,'Residential area'),required(d.leader,'Leader'),str(d.assistant),str(d.meeting)||'Sunday, 5:00 pm');break;
case 'assign-group':{need(p.groups);const group=await q.prepare('SELECT id FROM groups WHERE id=$1 AND campus=$2').bind(str(d.groupId),campus).first();const member=await q.prepare('SELECT id FROM members WHERE id=$1 AND campus=$2').bind(str(d.memberId),campus).first();if(!group||!member)throw new Error('Select a member and group in this campus.');statement=q.prepare('INSERT INTO group_members(id,campus,group_id,member_id) SELECT $1,$2,$3,$4 WHERE (SELECT COUNT(*) FROM group_members WHERE group_id=$5)<10').bind(id,campus,d.groupId,d.memberId,d.groupId);const outcome=await q.batch([statement,await auditStatement(campus,'Koinonia assignment requested',id,author)]);if(!outcome[0].meta.changes)throw new Error('This group has reached its limit of 10 members.');return Response.json({ok:true,id});}
case 'vow':{need(p.finance||!!ctx.member);const memberId=p.finance?str(d.memberId):ctx.member.id;const member=await q.prepare('SELECT id FROM members WHERE id=$1 AND campus=$2').bind(memberId,campus).first();if(!member)throw new Error('Select a member.');const amount=num(d.amount);if(!amount)throw new Error('Amount must be greater than zero.');statement=q.prepare('INSERT INTO vows(id,campus,member_id,purpose,amount,date) VALUES($1,$2,$3,$4,$5,$6)').bind(id,campus,memberId,required(d.purpose,'Purpose'),amount,date(d.date));break;}
case 'transaction':{need(p.finance);const amount=num(d.amount);if(!amount)throw new Error('Amount must be greater than zero.');if(!['Income','Expense','Cash to bank','Bank to cash','Opening balance'].includes(d.type))throw new Error('Select a transaction type.');if(!['Cash','Bank'].includes(d.account))throw new Error('Select an account.');let vowId=null;if(d.vowId){if(d.type!=='Income')throw new Error('Vow payments must be income.');const vow=await q.prepare('SELECT id FROM vows WHERE id=$1 AND campus=$2').bind(str(d.vowId),campus).first();if(!vow)throw new Error('Vow not found in this campus.');vowId=d.vowId;}if(vowId){const s=q.prepare('INSERT INTO transactions(id,campus,type,account,amount,category,description,date,vow_id,author,created_at) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11 WHERE $12<=(SELECT amount FROM vows WHERE id=$13 AND campus=$14)-COALESCE((SELECT SUM(amount) FROM transactions WHERE vow_id=$15 AND campus=$16),0)').bind(id,campus,d.type,d.account,amount,required(d.category,'Category'),required(d.description,'Description'),date(d.date),vowId,author,now,amount,vowId,campus,vowId,campus);const r=await q.batch([s,await auditStatement(campus,'Vow payment requested',id,author)]);if(!r[0].meta.changes)throw new Error('The payment exceeds the outstanding vow balance.');return Response.json({ok:true,id});}statement=q.prepare('INSERT INTO transactions(id,campus,type,account,amount,category,description,date,vow_id,author,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)').bind(id,campus,d.type,d.account,amount,required(d.category,'Category'),required(d.description,'Description'),date(d.date),vowId,author,now);break;}
case 'announcement':need(p.announcements);if(!['All members',...departments].includes(d.audience))throw new Error('Select an audience.');statement=q.prepare('INSERT INTO announcements(id,campus,title,body,audience,date,author) VALUES($1,$2,$3,$4,$5,$6,$7)').bind(id,campus,required(d.title,'Title'),required(d.body,'Message').slice(0,500),d.audience,date(d.date),author);break;
case 'grant':need(p.admin);if(!roles.includes(d.role))throw new Error('Select a role.');const email=required(d.email,'Email').toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('Enter a valid email address.');statement=q.prepare('INSERT INTO grants(id,campus,email,role) VALUES($1,$2,$3,$4) ON CONFLICT(email,campus) DO UPDATE SET role=excluded.role').bind(id,campus,email,d.role);break;
case 'campus':need(p.admin);statement=q.prepare('INSERT INTO campuses(id,name,town,region) VALUES($1,$2,$3,$4)').bind(id,required(d.name,'Campus name'),required(d.town,'Town'),required(d.region,'Region'));break;
default:throw new Error('Unknown action.');}
await q.batch([statement,await auditStatement(campus,b.action,resultId,author)]);return Response.json({ok:true,id:resultId});
}catch(e){return fail(e);}}
