'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export function InviteAccount({campus}:{campus:string}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[invite,setInvite]=useState<{code:string,email:string}|null>(null);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const email=new FormData(e.currentTarget).get('email');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'invite',campus,email})});const body=await r.json() as any;if(!r.ok)throw new Error(body.error);setInvite(body);}catch(e){setError(e instanceof Error?e.message:'Unable to create invitation.');}finally{setBusy(false);}}
 return <><button className="btn secondary" onClick={()=>{setInvite(null);setError('');setOpen(true);}}>Create account invitation</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="record-dialog"><DialogHeader><DialogTitle>Invite a member</DialogTitle><DialogDescription>Share this code privately with the person using this email. No email is sent automatically.</DialogDescription></DialogHeader>{invite?<div className="auth-form"><strong>{invite.email}</strong><label>Invitation code<input readOnly value={invite.code} onFocus={e=>e.target.select()}/></label><p>Valid for seven days. Ask the member to open this website and select Activate account. Assign officer roles separately under Campus responsibilities.</p></div>:<form className="auth-form" onSubmit={submit}><label>Member’s email<input name="email" type="email" required/></label>{error&&<p role="alert" className="auth-error">{error}</p>}<button className="btn primary" disabled={busy}>{busy?'Creating…':'Create invitation'}</button></form>}</DialogContent></Dialog></>;
}
export function ChangePassword(){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));if(data.password!==data.confirm){setMessage('Your passwords do not match.');setBusy(false);return;}try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,action:'password'})});const body=await r.json() as any;if(!r.ok)throw new Error(body.error);form.reset();setMessage('Password updated.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to change password.');}finally{setBusy(false);}}
 return <><button className="btn secondary" onClick={()=>{setMessage('');setOpen(true);}}>Change password</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="record-dialog"><DialogHeader><DialogTitle>Change your password</DialogTitle><DialogDescription>Use at least 12 characters.</DialogDescription></DialogHeader><form className="auth-form" onSubmit={submit}><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" maxLength={128} required/></label><label>New password<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></label><label>Confirm password<input name="confirm" type="password" autoComplete="new-password" minLength={12} maxLength={128} required/></label>{message&&<p role="status">{message}</p>}<button className="btn primary" disabled={busy}>{busy?'Saving…':'Update password'}</button></form></DialogContent></Dialog></>;
}
